Repository Colm3na/polkastats-v2, pull requests merged in 2020-03, with the labels that each got.

#82 #69 Finish Polkadot identity support
  package-lock.json
  pages/intention/index.vue
  pages/nominator/index.vue
  pages/phragmen-candidate/index.vue
  pages/validator/index.vue
Labels: V2_PENDING, ux

#89 statistical data in the home page only
  pages/account/index.vue
  pages/accounts.vue
  pages/favorites.vue
  pages/intentions.vue
  pages/phragmen.vue
Labels: ux

#103 Fix Phragmen candidate
  pages/phragmen-candidate/index.vue
Labels: bug

#109 #108 Add Github templates
  .github/CODE_OWNERS
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#120 Validator Table subscription
  pages/index.vue
  pages/validators.vue
  store/validators.js
Labels: enhancement
